// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg1DgM5WsDK9g1jZpYcx9sXDOI-9-b7tE',
    appId: '1:884895850956:web:1f05ce1d94fd74f4dffd69',
    messagingSenderId: '884895850956',
    projectId: 'aws-demo-a0336',
    authDomain: 'aws-demo-a0336.firebaseapp.com',
    storageBucket: 'aws-demo-a0336.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT3wggSeJvWaf-oqeRQdv0Jk21udEnd5s',
    appId: '1:884895850956:android:5bd28bf4728980b3dffd69',
    messagingSenderId: '884895850956',
    projectId: 'aws-demo-a0336',
    storageBucket: 'aws-demo-a0336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDliHXVf20gCScMLt1d9Z0kV_9_Bg4Zjl4',
    appId: '1:884895850956:ios:61fe1728e1169ccbdffd69',
    messagingSenderId: '884895850956',
    projectId: 'aws-demo-a0336',
    storageBucket: 'aws-demo-a0336.appspot.com',
    iosBundleId: 'com.xqu.awsDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDliHXVf20gCScMLt1d9Z0kV_9_Bg4Zjl4',
    appId: '1:884895850956:ios:61fe1728e1169ccbdffd69',
    messagingSenderId: '884895850956',
    projectId: 'aws-demo-a0336',
    storageBucket: 'aws-demo-a0336.appspot.com',
    iosBundleId: 'com.xqu.awsDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg1DgM5WsDK9g1jZpYcx9sXDOI-9-b7tE',
    appId: '1:884895850956:web:158b138ba508e949dffd69',
    messagingSenderId: '884895850956',
    projectId: 'aws-demo-a0336',
    authDomain: 'aws-demo-a0336.firebaseapp.com',
    storageBucket: 'aws-demo-a0336.appspot.com',
  );

}